# data parameters

data_with_subfolder: False
# dataset_name: flickr8k
# train_data_path: /home/ec2-user/SageMaker/dataset/flickr8k/Images
dataset_name: celeba
train_data_path: /home/jupyter/dataset/img_celeba
val_data_path:
resume:
# batch_size: 48
batch_size: 8
image_shape: [256, 256, 3]
mask_shape: [128, 128]
mask_batch_same: True
max_delta_shape: [32, 32]
margin: [0, 0]
discounted_mask: True
spatial_discounting_gamma: 0.9
random_crop: False # Set False with celebA, True for datasets
mask_type: freeform    # hole | mosaic \ freeform
mosaic_unit_size: 12

#random free_form settings
maxvertex: 5
maxangle: 4.0 #pi
maxlength: 40
maxbrushwidth: 10
random_ff_settings:
    shape: [256,256]
    mv: 5
    ma: 4.0
    ml: 40
    mbw: 10

# training parameters
expname: benchmark
cuda: True
# gpu_ids: [0, 1, 2]    # set the GPU ids to use, e.g. [0] or [1, 2]
gpu_ids: [0, 1, 2, 3, 4, 5, 6, 7]
num_workers: 4
lr: 0.0001
beta1: 0.5
beta2: 0.99
n_critic: 2 # 5
print_iter: 2000
viz_iter: 5000
viz_max_out: 16
snapshot_save_iter: 20000
niter: 500000

# loss weight
coarse_l1_alpha: 1.2
l1_loss_alpha: 1.0 # 1.2
ae_loss_alpha: 1.2
global_wgan_loss_alpha: 1.
gan_loss_alpha: 1 #0.001
wgan_gp_lambda: 10

# network parameters
netG:
  input_dim: 3
  ngf: 48 # 32
  gated: True

netD:
  input_dim: 4  # 3 channels from output of generator, plus 1 from free-form mask.
  ndf: 64
  weight_norm: 'sn'  # spectral norm

